version: '3.7'
services:
  main:
    build:
      context: .
      target: development
    ports:
      - 4001:5000
    command: yarn start:dev
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8',
        '--collation-server=utf8_unicode_ci',
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    # ports:
    #   - ${MYSQL_PORT}:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.4
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 64M
    networks:
      - backend
    ports:
      - 8080:80
    depends_on:
      - mysql

networks:
  backend:
volumes:
  data:
